using Superpower.Model;
using JustyBase.NetezzaSqlParser.Lexer;
using JustyBase.NetezzaSqlParser.Ast;

namespace JustyBase.NetezzaSqlParser.Parser;

public partial class Db2SqlParser
{
    protected override (DistributeClause? Distribute, OrganizeClause? Organize) ParseTableStorageClauses()
    {
        var k = Peek().Kind;
        if (k is NzToken.Distribute or NzToken.Organize)
        {
            AddParserError($"{k} is Netezza-only syntax and is not supported in Db2",
                Peek(), "PAR001");
            // Still consume via base so the statement does not leave NZ tokens behind.
            _ = base.ParseTableStorageClauses();
        }

        // Db2 table options (ORGANIZE BY / DATA CAPTURE / …) fall through as an
        // opaque tail — mirrors commandTail in the reference parser.ts.
        ParseDb2CreateTableOptionTail();
        return (null, null);
    }

    private void ParseDb2CreateTableOptionTail()
    {
        while (Peek().Kind is NzToken.Db2OrganizeBy or NzToken.Db2DataCapture)
        {
            Advance();
            while (!IsDb2CreateTableOptionStop())
            {
                if (Peek().Kind == NzToken.LParen)
                {
                    Advance();
                    var depth = 1;
                    while (depth > 0 && Peek().Kind != NzToken.Unknown)
                    {
                        if (Peek().Kind == NzToken.LParen) depth++;
                        else if (Peek().Kind == NzToken.RParen) depth--;
                        Advance();
                    }
                }
                else
                {
                    Advance();
                }
            }
        }
    }

    private bool IsDb2CreateTableOptionStop()
    {
        var k = Peek().Kind;
        if (k is NzToken.Semicolon or NzToken.Unknown
            or NzToken.Db2OrganizeBy or NzToken.Db2DataCapture)
            return true;

        // Next top-level statement without a separating semicolon.
        return k is NzToken.Select or NzToken.With or NzToken.Insert or NzToken.Update
            or NzToken.Delete or NzToken.Create or NzToken.Drop or NzToken.Alter
            or NzToken.Truncate or NzToken.Merge or NzToken.Call
            or NzToken.Db2DeclareGlobalTemporary or NzToken.Groom or NzToken.Generate
            or NzToken.Commit or NzToken.Rollback or NzToken.Grant or NzToken.Revoke;
    }

    protected override bool IsDialectColumnClauseStart() =>
        Peek().Kind is NzToken.Db2GeneratedAlways or NzToken.Db2GeneratedByDefault
            or NzToken.Db2Identity;

    protected override bool TryParseDialectColumnClause()
    {
        if (!IsDialectColumnClauseStart())
            return false;

        // GENERATED ALWAYS | GENERATED BY DEFAULT [AS] IDENTITY [(…)]
        if (Peek().Kind is NzToken.Db2GeneratedAlways or NzToken.Db2GeneratedByDefault)
            Advance();
        if (Peek().Kind == NzToken.As)
            Advance();
        if (Peek().Kind == NzToken.Db2Identity)
            Advance();
        if (Peek().Kind == NzToken.LParen)
        {
            Advance();
            var depth = 1;
            while (depth > 0 && Peek().Kind != NzToken.Unknown)
            {
                if (Peek().Kind == NzToken.LParen) depth++;
                else if (Peek().Kind == NzToken.RParen) depth--;
                Advance();
            }
        }

        return true;
    }

    protected override Expression? TryParseDialectPrimary()
    {
        var t = Peek();
        if (t.Kind is NzToken.Db2CurrentDate or NzToken.Db2CurrentTime
            or NzToken.Db2CurrentTimestamp or NzToken.Db2CurrentUser
            or NzToken.Db2CurrentSchema or NzToken.Db2CurrentServer)
        {
            Advance();
            // Surface as a bare column/special-value reference (same shape as
            // CURRENT_DATE identifiers under the Netezza lexer).
            return new ColumnReference(FromToken(t), null, t.ToStringValue().Trim());
        }

        return null;
    }
}
