using System.Text.Json.Serialization;

namespace JustyBase.NetezzaSqlLsp.Protocol;

[JsonSourceGenerationOptions(
    WriteIndented = false,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
)]
[JsonSerializable(typeof(JsonRpcRequest))]
[JsonSerializable(typeof(JsonRpcResponse))]
[JsonSerializable(typeof(JsonRpcNotification))]
[JsonSerializable(typeof(JsonRpcError))]
[JsonSerializable(typeof(object))]
[JsonSerializable(typeof(InitializeParams))]
[JsonSerializable(typeof(InitializeResult))]
[JsonSerializable(typeof(ServerCapabilities))]
[JsonSerializable(typeof(ServerInfo))]
[JsonSerializable(typeof(CompletionOptions))]
[JsonSerializable(typeof(DiagnosticOptions))]
[JsonSerializable(typeof(SemanticTokensOptions))]
[JsonSerializable(typeof(SemanticTokensLegend))]
[JsonSerializable(typeof(CompletionParams))]
[JsonSerializable(typeof(CompletionList))]
[JsonSerializable(typeof(CompletionItem))]
[JsonSerializable(typeof(PublishDiagnosticsParams))]
[JsonSerializable(typeof(Diagnostic))]
[JsonSerializable(typeof(DidOpenTextDocumentParams))]
[JsonSerializable(typeof(DidChangeTextDocumentParams))]
[JsonSerializable(typeof(DidCloseTextDocumentParams))]
[JsonSerializable(typeof(TextDocumentItem))]
[JsonSerializable(typeof(VersionedTextDocumentIdentifier))]
[JsonSerializable(typeof(TextDocumentContentChangeEvent))]
[JsonSerializable(typeof(SemanticTokensParams))]
[JsonSerializable(typeof(SemanticTokensResult))]
[JsonSerializable(typeof(HoverParams))]
[JsonSerializable(typeof(Hover))]
[JsonSerializable(typeof(MarkupContent))]
[JsonSerializable(typeof(Location))]
[JsonSerializable(typeof(Location[]))]
[JsonSerializable(typeof(DefinitionParams))]
[JsonSerializable(typeof(ReferenceParams))]
[JsonSerializable(typeof(ReferenceContext))]
[JsonSerializable(typeof(DocumentSymbolParams))]
[JsonSerializable(typeof(SymbolInformation))]
[JsonSerializable(typeof(SymbolInformation[]))]
[JsonSerializable(typeof(SignatureHelpOptions))]
[JsonSerializable(typeof(SignatureHelpParams))]
[JsonSerializable(typeof(SignatureHelp))]
[JsonSerializable(typeof(SignatureInformation))]
[JsonSerializable(typeof(ParameterInformation))]
[JsonSerializable(typeof(SyncSchemaParams))]
[JsonSerializable(typeof(TableSchema))]
[JsonSerializable(typeof(ColumnSchema))]
[JsonSerializable(typeof(TextDocumentIdentifier))]
[JsonSerializable(typeof(RenameParams))]
[JsonSerializable(typeof(PrepareRenameParams))]
[JsonSerializable(typeof(PrepareRenameResult))]
[JsonSerializable(typeof(WorkspaceEdit))]
[JsonSerializable(typeof(TextEdit))]
[JsonSerializable(typeof(TextEdit[]))]
public partial class LspJsonContext : JsonSerializerContext { }
