using JustyBase.NetezzaSqlParser.Caching;

namespace JustyBase.NetezzaSql.Tests;

public sealed class ReferenceInvalidParserCorpusTests
{
    public static IEnumerable<object[]> InvalidSql =
    new object[][]
    {
        new object[] { "ALTER TABLE TESTDB..EMPLOYEES;" },
        new object[] { "CREATE MATERIALIZED VIEW ADMIN.COLOR_CHECK_MV AS;" },
        new object[] { "CREATE MATERIALIZED VIEW ADMIN.COLOR_CHECK_MV AS ()" },
        new object[] { "CREATE TABLE (ID INT4);" },
        new object[] { "CREATE TABLE t (col1)" },
        new object[] { "CREATE TABLE t (id INT, name VARCHAR(100)" },
        new object[] { "CREATE TABLE t (id INT,, name VARCHAR(100))" },
        new object[] { "CREATE TABLE T_NEW (SELECT 1 AS COL);" },
        new object[] { "CREATE TABLE T_NEW AS;" },
        new object[] { "CREATE TABLE T1 ();" },
        new object[] { "CREATE TABLE T1 (ID);" },
        new object[] { "CREATE TABLE T1 (INT4);" },
        new object[] { "CREATE TABLE TESTDB..NEW_TABLE;" },
        new object[] { "CREATE TABLE TESTDB..T AS (SELECT 1 AS COL;" },
        new object[] { "CREATE VIEW V_EMP (ID,) AS SELECT 1 AS ID;" },
        new object[] { "CREATE VIEW V_EMP AS;" },
        new object[] { "CREATE VIEW V_EMP SELECT 1;" },
        new object[] { "CTE AS (SELECT 1) SELECT * FROM CTE;" },
        new object[] { "DELETE FROM TESTDB..FILMS WHERE CODE = ;" },
        new object[] { "DELETE FROM TESTDB..FILMS WHERE;" },
        new object[] { "DELETE FROM WHERE CODE = 'A';" },
        new object[] { "DELETE FROM WHERE EMPLOYEE_ID = 1;" },
        new object[] { "DELETE TESTDB..EMPLOYEES WHERE EMPLOYEE_ID = 1;" },
        new object[] { "DELETE TESTDB..FILMS WHERE CODE = 1;" },
        new object[] { "DROP TABLE T1 IF;" },
        new object[] { "DROP TABLE;" },
        new object[] { "DROP TESTDB..EMPLOYEES;" },
        new object[] { "GRANT" },
        new object[] { "INSERT INTO TESTDB..FILMS ('A', 'B');" },
        new object[] { "INSERT INTO TESTDB..FILMS () VALUES ('A');" },
        new object[] { "INSERT INTO TESTDB..FILMS (CODE) VALUES ();" },
        new object[] { "INSERT INTO TESTDB..FILMS (CODE);" },
        new object[] { "INSERT INTO TESTDB..FILMS VALUES 'A', 'B';" },
        new object[] { "INSERT INTO TESTDB..FILMS VALUES 1, 'test';" },
        new object[] { "INSERT INTO VALUES (1, 'test');" },
        new object[] { "INSERT TESTDB..FILMS VALUES ('A', 'B');" },
        new object[] { "INSERT TESTDB..FILMS;" },
        new object[] { "REVOKE" },
        new object[] { "SELCET 1;" },
        new object[] { "SELECT 'unclosed string;" },
        new object[] { "SELECT ((a + b) * c FROM t;" },
        new object[] { "SELECT (1 + 2 AS X;" },
        new object[] { "SELECT (1 + 2;" },
        new object[] { "SELECT (1 + 2)) AS X;" },
        new object[] { "SELECT * FROM (SELECT 1 AS X;" },
        new object[] { "SELECT * FROM EMPLOYEES ORDER BY SALARY NULLS;" },
        new object[] { "SELECT * FROM FROM TESTDB..EMPLOYEES;" },
        new object[] { "SELECT * FROM SELECT 1 AS X) S;" },
        new object[] { "SELECT * FROM t LIMIT" },
        new object[] { "SELECT * FROM t WHERE id IN (1, 2, 3;" },
        new object[] { "SELECT * FROM t1 INNER JOIN ON t1.id = 1" },
        new object[] { "SELECT * FROM t1 JOIN t2 ON ON t1.id = t2.id" },
        new object[] { "SELECT * FROM t1 JOIN t2 ON t1.id =" },
        new object[] { "SELECT * FROM t1 LEFT JOIN" },
        new object[] { "SELECT * FROM t1 LEFT RIGHT JOIN t2 ON t1.id = t2.id" },
        new object[] { "SELECT * FROM TESTDB..EMPLOYEES GROUP BY;" },
        new object[] { "SELECT * FROM TESTDB..EMPLOYEES LIMIT;" },
        new object[] { "SELECT * FROM TESTDB..EMPLOYEES ORDER BY;" },
        new object[] { "SELECT * FROM TESTDB..EMPLOYEES WHER SALARY > 100;" },
        new object[] { "SELECT * FROM TESTDB..EMPLOYEES WHERE SALARY = ;" },
        new object[] { "SELECT * FROM TESTDB..EMPLOYEES WHERE;" },
        new object[] { "SELECT * FROM;" },
        new object[] { "SELECT 1 + 2) AS X;" },
        new object[] { "SELECT 1 + 2);" },
        new object[] { "SELECT 1 AS;" },
        new object[] { "SELECT 1 FORM TESTDB..EMPLOYEES;" },
        new object[] { "SELECT 1, , 2;" },
        new object[] { "SELECT 1, 2, FROM TESTDB..EMPLOYEES;" },
        new object[] { "SELECT CASE 1 = 1 THEN 'yes' END;" },
        new object[] { "SELECT CASE WHEN (1 = 1 THEN 'yes' END;" },
        new object[] { "SELECT CASE WHEN 1 = 1 'yes' END;" },
        new object[] { "SELECT CASE WHEN 1 = 1 THEN 'yes';" },
        new object[] { "SELECT COUNT(;" },
        new object[] { "SELECT COUNT(*) FROM t GROUP BY" },
        new object[] { "SELECT COUNT(*) FROM t GROUP BY id HAVING" },
        new object[] { "SELECT DISTINCT DISTINCT id FROM t" },
        new object[] { "SELECT EMPLOYEE_ID TESTDB..EMPLOYEES;" },
        new object[] { "SELECT FROM TESTDB..EMPLOYEES;" },
        new object[] { "SELECT id FROM t ORDER BY id," },
        new object[] { "SELECT id WHERE x > 1 FROM t" },
        new object[] { "SELECT SUM(x) OVER (PARTITION BY) FROM t" },
        new object[] { "SELECT SUM(x) OVER FROM t" },
        new object[] { "SELECT UPPER(name FROM TESTDB..EMPLOYEES;" },
        new object[] { "SELECT UPPER(name)) FROM TESTDB..EMPLOYEES;" },
        new object[] { "UPDATE JUST_DATA..DIMACCOUNT A WHERE A.ACCOUNTCODEALTERNATEKEY = 1;" },
        new object[] { "UPDATE SET KIND = 'Dramatic';" },
        new object[] { "UPDATE SET SALARY = 5000;" },
        new object[] { "UPDATE TESTDB..EMPLOYEES SALARY = 5000;" },
        new object[] { "UPDATE TESTDB..EMPLOYEES SET = 5000;" },
        new object[] { "UPDATE TESTDB..EMPLOYEES SET SALARY = 5000 WHERE;" },
        new object[] { "UPDATE TESTDB..EMPLOYEES SET SALARY == 5000;" },
        new object[] { "UPDATE TESTDB..FILMS KIND = 'Dramatic';" },
        new object[] { "UPDATE TESTDB..FILMS SET KIND 'Dramatic';" },
        new object[] { "UPDATE TESTDB..FILMS SET KIND = 'A',, TITLE = 'B';" },
        new object[] { "UPDATE TESTDB..FILMS SET KIND = WHERE CODE = 'A';" },
        new object[] { "WITH AS (SELECT 1 AS VAL) SELECT 1;" },
        new object[] { "WITH cte () AS (SELECT 1) SELECT * FROM cte" },
        new object[] { "WITH CTE (SELECT 1 AS VAL) SELECT * FROM CTE;" },
        new object[] { "WITH cte (SELECT 1) SELECT * FROM cte" },
        new object[] { "WITH CTE AS () SELECT 1;" },
        new object[] { "WITH CTE AS (SELECT 1 AS VAL), SELECT * FROM CTE;" },
        new object[] { "WITH CTE AS (SELECT 1 AS VAL);" },
        new object[] { "WITH CTE AS (SELECT 1 SELECT * FROM CTE;" },
        new object[] { "WITH CTE AS (SELECT 1);" },
        new object[] { "WITH CTE AS AS (SELECT 1) SELECT * FROM CTE;" },
        new object[] { "WITH cte AS SELECT * FROM cte" },
        new object[] { "WITH CTE AS SELECT 1 AS VAL SELECT * FROM CTE;" },
    };

    [Theory]
    [MemberData(nameof(InvalidSql))]
    public void ReferenceSqlParserCase_ReportsSyntaxError(string sql)
    {
        using var runtime = new ParsingRuntime();
        var result = runtime.Parse(sql);
        Assert.False(result.Valid, "Expected syntax error for SQL=" + sql);
    }
}
